# -*- coding: utf-8 -*-
"""Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lr7KK6bnmjBC6srzeWTKofNHw8gMUlas

# Basics
"""

greeting= 'hello world'
print(greeting)

"""# Operators"""

# arithematic  operator
print(4+4)
print(4-4)
print(4*4)
print(4/4)
print(5//2) #integer division
print(5%2)
print(5**2) #power off operator
a=2     # assignment operator
a += 8
print(a)
print("kinza "+"Ayaz")   #string concatenantion

# relational operators
print(4>5)
print(4<5)
print(4>=5)
print(4<=5)
print(4==5)
print(4!=5)

# logical operators
print(1 and 0)
print(1 or 1)
print(not 1)

"""# If else using comparison operator"""

age=28
if age>18:
  print("you are an adult")
else:
  print("you are a teenager")

"""# Ternary operator"""

age=20
print("you are an adult") if age>18 else print("you are a teenager")

s = ""
message = "Empty" if s == "" else "Not Empty"
print(message)

"""# Data types"""

#string
Name="python"
print(type(Name))
print(type(Name)==str)
print(isinstance(Name,str))

"""# Numeric datatype"""

# int
age=25
print(type(age))

# float
num=float(6)
print(type(num))

#complex
comp_val=3+7j
print(type(comp_val))
print(comp_val.real)
print(type(comp_val.imag))

# concatenation
firstName="kinza"
lastName="Ayaz"
result=firstName+" "+lastName
result+="!"
print(result)

"""# Type casting"""

# casting a number to string
year=str(1980)
print(type(year))
statment="I like rock music from year "+year+ "s."
print(statment)

# casting a number to string
num=str(10)
print(type(num))

# for multilines
multiLines="""
hey,how are you?

I'm fine.
                 Ehmmmm

"""
print(multiLines)

"""# Escape sequence"""

# escaping the special characters
sentence='I\'m back at work\n\t Hey!\n where\'s this at\\located?'
print(sentence)

"""# String methods"""

print(" Kinza".upper())
print(" KiNza".lower())
print("My name is kinza".title())
print("kinza".islower())
print("KInza".isupper())
print("KInza".isalpha())
print("KInza".isdecimal())

string="These are string methods"
print("hii" in string)         #in operator

print(string.startswith("T"))
print(string.endswith("."))

myString="My name is kinza"
print(myString.replace("kinza","KiNza"))
print(myString)
print(len(myString))      #len()
myString+="          "
myString= "                  " +myString
print(len(myString))

print(len(myString.strip()))         #strip()
print(len(myString.lstrip()))        #white spaces from left spaces
print(len(myString.rstrip()))         #white spaces from right spaces

"""# Build a menu"""

title="menu".upper()
print(title.center(20,"="))
print("coffee".ljust(16,".") + "$1".rjust(4))
print("Cupcake".ljust(16,".") + "$4".rjust(4))
print("Muffins".ljust(16,".") + "$2".rjust(4))

"""# Indexing"""

name="kinza"
print(name[0])
print(name[0:3])
print(name[1:-1])
print(name[1:])
print(name[::2])